# Generated by Django 3.2.9 on 2021-11-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0002_alter_book_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
