# Generated by Django 3.2.9 on 2021-12-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0003_book_total_rental'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'categories'},
        ),
    ]
