# Generated by Django 3.2.9 on 2021-12-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categories'},
        ),
    ]
